import { Button } from "@/components/ui/button";
import { Download, Bot, Terminal, KeyRound, FileText, Sparkles } from "lucide-react";
import JSZip from "jszip";
import { toast } from "sonner";

interface Props {
  files: Record<string, string>;
  projectTitle: string;
}

export function BotInfoPane({ files, projectTitle }: Props) {
  const paths = Object.keys(files).sort();
  const hasFiles = paths.length > 0;

  let pkgJson: any = null;
  if (files["package.json"]) {
    try { pkgJson = JSON.parse(files["package.json"]); } catch { /* ignore */ }
  }

  const commandFiles = paths.filter((p) => p.startsWith("src/commands/"));
  const eventFiles = paths.filter((p) => p.startsWith("src/events/"));
  const deps = pkgJson?.dependencies ? Object.entries(pkgJson.dependencies) as [string, string][] : [];

  async function exportZip() {
    if (!hasFiles) return;
    const zip = new JSZip();
    for (const [path, content] of Object.entries(files)) {
      zip.file(path, content);
    }
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectTitle.replace(/[^a-z0-9-_]+/gi, "-").toLowerCase() || "bot"}.zip`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    toast.success("Project exported");
  }

  return (
    <div className="flex h-full flex-col bg-muted/30">
      <div className="flex items-center justify-between border-b bg-background px-4 py-2.5">
        <div className="flex items-center gap-2 text-sm font-medium">
          <Bot className="h-4 w-4 text-primary" /> Bot Overview
        </div>
        <Button size="sm" onClick={exportZip} disabled={!hasFiles} className="bg-gradient-to-r from-primary to-primary-glow">
          <Download className="mr-1.5 h-3.5 w-3.5" /> Export ZIP
        </Button>
      </div>

      <div className="flex-1 overflow-y-auto px-4 py-5 sm:px-6">
        {!hasFiles ? (
          <div className="mx-auto flex max-w-md flex-col items-center pt-16 text-center">
            <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-primary-glow shadow-lg shadow-primary/30">
              <Sparkles className="h-6 w-6 text-white" />
            </div>
            <h3 className="text-lg font-semibold">Describe your Discord bot</h3>
            <p className="mt-1.5 text-sm text-muted-foreground">
              Try: <em>"Create a moderation bot with warn, mute, kick, ban"</em>,
              &nbsp;<em>"Add a ticket system"</em>, or <em>"Add an economy with daily rewards"</em>.
            </p>
          </div>
        ) : (
          <div className="mx-auto max-w-2xl space-y-5">
            <Card icon={<FileText className="h-4 w-4" />} title={pkgJson?.name ?? projectTitle}>
              <p className="text-sm text-muted-foreground">
                {pkgJson?.description ?? "Discord bot project generated by Lumo."}
              </p>
              <div className="mt-3 grid grid-cols-3 gap-2 text-center">
                <Stat label="Files" value={paths.length} />
                <Stat label="Commands" value={commandFiles.length} />
                <Stat label="Events" value={eventFiles.length} />
              </div>
            </Card>

            <Card icon={<Terminal className="h-4 w-4" />} title="Run locally">
              <ol className="space-y-1.5 text-sm text-muted-foreground">
                <li><span className="text-foreground">1.</span> Export the ZIP and unzip it.</li>
                <li><span className="text-foreground">2.</span> <code className="rounded bg-surface-2 px-1.5 py-0.5 text-xs">npm install</code></li>
                <li><span className="text-foreground">3.</span> Copy <code className="rounded bg-surface-2 px-1.5 py-0.5 text-xs">.env.example</code> → <code className="rounded bg-surface-2 px-1.5 py-0.5 text-xs">.env</code> and add your bot token.</li>
                <li><span className="text-foreground">4.</span> <code className="rounded bg-surface-2 px-1.5 py-0.5 text-xs">node src/deploy-commands.js</code> (register slash commands)</li>
                <li><span className="text-foreground">5.</span> <code className="rounded bg-surface-2 px-1.5 py-0.5 text-xs">npm start</code></li>
              </ol>
            </Card>

            {deps.length > 0 && (
              <Card icon={<KeyRound className="h-4 w-4" />} title="Dependencies">
                <div className="flex flex-wrap gap-1.5">
                  {deps.map(([name, ver]) => (
                    <span key={name} className="rounded-md border border-border bg-surface-2 px-2 py-0.5 text-xs font-mono">
                      {name}<span className="text-muted-foreground"> {String(ver)}</span>
                    </span>
                  ))}
                </div>
              </Card>
            )}

            {commandFiles.length > 0 && (
              <Card icon={<Bot className="h-4 w-4" />} title={`Slash commands (${commandFiles.length})`}>
                <ul className="grid gap-1 sm:grid-cols-2">
                  {commandFiles.map((p) => (
                    <li key={p} className="truncate rounded-md bg-surface-2 px-2 py-1 text-xs font-mono">
                      /{p.split("/").pop()?.replace(/\.[jt]sx?$/, "")}
                    </li>
                  ))}
                </ul>
              </Card>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function Card({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-border bg-card/60 p-4">
      <div className="mb-3 flex items-center gap-2 text-sm font-semibold">
        <span className="text-primary">{icon}</span>
        {title}
      </div>
      {children}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-lg bg-surface-2 py-2">
      <div className="text-lg font-semibold">{value}</div>
      <div className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</div>
    </div>
  );
}
